Device found
Total features gathered 1408034, problem size: 1408034
Traceback (most recent call last):
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/generate_proxy_training_labels.py", line 49, in <module>
    main(None)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/generate_proxy_training_labels.py", line 45, in main
    k_means = KMeansModule(K=7806, dimensionality=768, config=config, resources=resources)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/src/k_means.py", line 22, in __init__
    self.kmeans = faiss.Kmeans(
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/faiss/extra_wrappers.py", line 489, in __init__
    getattr(self.cp, k)
AttributeError: 'ClusteringParameters' object has no attribute 'gpu_resource'
